name = "sparsePolyChaos"
uuid = "b14ff7f8-8c6a-417b-bc18-4148be3220ad"
authors = ["Adrian Grupp <adrian.grupp@posteo.net>"]
version = "0.1.0"

[deps]
PolyChaos = "8d666b04-775d-5f6e-b778-5ac7c70f65a3"
